#sudo: false

language: go

go:
  - 1.10.x

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

#before_install:
  #- go get -u golang.org/x/vgo

install:
  - go get ./...

#before_script:
  #- go get github.com/alecthomas/gometalinter

script:
  #- gometalinter --install
  #- gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor ./...
  - go test -v -race ./...

#after_script:

notifications:
  email: false