# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - "1.x"
  - "tip"

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

#before_install:

install:
  - go get -t ./...
  - go get github.com/alecthomas/gometalinter

#before_script:

script:
  - gometalinter --install
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor ./...
  - go test -v -race ./...

#after_script:

notifications:
  email: false