# WPdirectory Example Config
host: http://localhost/
updateworkers: 2
searchworkers: 6
ports:
  http: 11001
  https: 11002

# Add Admin Users
users:
  - username: username1
    password: password1
  - username: username2
    password: password2
