# WPdirectory Example Config
workers: 50
buffersize: 200
datadir: data
indexdir: index
standalone: false # if true overwrites ports to 80/443
ports:
  http: 11001
  https: 11002

# Add Admin Users
users:
  - username: username1
    password: password1
  - username: username2
    password: password2
